version: "3.7"
services:
  apspil:
    build:
      args:
        user: rahanpas
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: begm3
    container_name: bepil-apspil
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - bepil

  nginx:
    image: nginx:alpine
    container_name: bepil-nginx
    restart: unless-stopped
    ports:
      - 2323:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - bepil

networks:
  bepil:
    driver: bridge
